sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

install:
  - echo "${TRAVIS_BRANCH}"
  - docker build -t alephdata/platform:${TRAVIS_TAG} .

script:
  - sleep 1

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      docker push alephdata/platform:${TRAVIS_TAG} ;
    fi
