sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t alephdata/platform:$TRAVIS_BRANCH .
  - docker build -t alephdata/platform-polyglot:$TRAVIS_BRANCH polyglot
  - docker build -t alephdata/platform-elasticsearch:$TRAVIS_BRANCH elasticsearch

script:
  - sleep 1

after_success:
  # push if it's a tagged build.
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      docker push alephdata/platform:$TRAVIS_BRANCH ;
      docker push alephdata/platform-polyglot:$TRAVIS_BRANCH ;
      docker push alephdata/platform-elasticsearch:$TRAVIS_BRANCH ;
    fi
