sudo: required
language: python

env:
  - IMAGE=alephdata/platform CONTEXT=aleph
  - IMAGE=alephdata/platform-polyglot CONTEXT=polyglot
  - IMAGE=alephdata/platform-elasticsearch CONTEXT=elasticsearch
  - IMAGE=alephdata/platform-libreoffice CONTEXT=libreoffice
  - IMAGE=alephdata/platform-spacy CONTEXT=spacy

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo $IMAGE
  - echo $CONTEXT
  - echo $TRAVIS_BRANCH
  - docker build -t $IMAGE:latest $CONTEXT

script:
  - sleep 1

after_success:
  # push if it's a tagged build.
  - docker push $IMAGE:latest
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      docker tag $IMAGE:latest $IMAGE:$TRAVIS_BRANCH ;
      docker push $IMAGE:$TRAVIS_BRANCH ;
    fi
