sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t alephdata/platform:$TRAVIS_BRANCH .
  # - cd elasticsearch && make push

script:
  - sleep 1

after_success:
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      docker push alephdata/platform:$TRAVIS_BRANCH ;
    fi
